/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurantathand.client.presentation;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Michelle Vallejo
 */
public class GUIRegistrarCustomer extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistrarCustomer
     */
    public GUIRegistrarCustomer() 
    {
        initComponents();
        setLocationRelativeTo(null);
        initIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        pnlColorCustomer = new javax.swing.JPanel();
        lblColorCust = new javax.swing.JLabel();
        pnlRegistrarCust = new javax.swing.JPanel();
        lblCheckCust = new javax.swing.JLabel();
        lblUserNameCus = new javax.swing.JLabel();
        lblIdCus = new javax.swing.JLabel();
        lblNameCus = new javax.swing.JLabel();
        lblLastnameCus = new javax.swing.JLabel();
        lblPasswordCus = new javax.swing.JLabel();
        lblCityCus = new javax.swing.JLabel();
        lblAddressCus = new javax.swing.JLabel();
        lblPhoneCus = new javax.swing.JLabel();
        lblTypeCus = new javax.swing.JLabel();
        txtUserNameCust = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdCust = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtNameCust = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtPasswordCust = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtCityCust = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtAddressCust = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtPhoneCust = new javax.swing.JTextField();
        txtTypeCust = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btnRegistrarCust = new javax.swing.JButton();
        txtLastNameCust = new javax.swing.JTextField();
        btnAtrasCus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlColorCustomer.setBackground(new java.awt.Color(255, 255, 255));
        pnlColorCustomer.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlColorCustomer.setMinimumSize(new java.awt.Dimension(90, 440));
        pnlColorCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlColorCustomer.add(lblColorCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 720));

        getContentPane().add(pnlColorCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 88, 720));

        pnlRegistrarCust.setBackground(new java.awt.Color(255, 255, 255));

        lblUserNameCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblUserNameCus.setForeground(new java.awt.Color(102, 102, 102));
        lblUserNameCus.setText("User name:");

        lblIdCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblIdCus.setForeground(new java.awt.Color(102, 102, 102));
        lblIdCus.setText("Identification:");

        lblNameCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNameCus.setForeground(new java.awt.Color(102, 102, 102));
        lblNameCus.setText("Name:");

        lblLastnameCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblLastnameCus.setForeground(new java.awt.Color(102, 102, 102));
        lblLastnameCus.setText("Lastname:");

        lblPasswordCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblPasswordCus.setForeground(new java.awt.Color(102, 102, 102));
        lblPasswordCus.setText("Password:");

        lblCityCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCityCus.setForeground(new java.awt.Color(102, 102, 102));
        lblCityCus.setText("City:");

        lblAddressCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAddressCus.setForeground(new java.awt.Color(102, 102, 102));
        lblAddressCus.setText("Address:");

        lblPhoneCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblPhoneCus.setForeground(new java.awt.Color(102, 102, 102));
        lblPhoneCus.setText("Phone:");

        lblTypeCus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTypeCus.setForeground(new java.awt.Color(102, 102, 102));
        lblTypeCus.setText("Type:");

        txtUserNameCust.setBorder(null);

        txtIdCust.setBorder(null);

        txtNameCust.setBorder(null);

        txtPasswordCust.setBorder(null);

        txtCityCust.setBorder(null);

        txtAddressCust.setBorder(null);

        txtPhoneCust.setBorder(null);

        txtTypeCust.setBorder(null);

        btnRegistrarCust.setText("Check In");

        txtLastNameCust.setBorder(null);

        btnAtrasCus.setBackground(new java.awt.Color(255, 255, 255));
        btnAtrasCus.setForeground(new java.awt.Color(102, 102, 102));
        btnAtrasCus.setText("Back");
        btnAtrasCus.setBorder(null);

        javax.swing.GroupLayout pnlRegistrarCustLayout = new javax.swing.GroupLayout(pnlRegistrarCust);
        pnlRegistrarCust.setLayout(pnlRegistrarCustLayout);
        pnlRegistrarCustLayout.setHorizontalGroup(
            pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtrasCus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(lblCheckCust, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegistrarCust)
                            .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserNameCus)
                                    .addComponent(lblIdCus)
                                    .addComponent(lblNameCus)
                                    .addComponent(lblLastnameCus)
                                    .addComponent(lblPasswordCus)
                                    .addComponent(lblCityCus)
                                    .addComponent(lblAddressCus)
                                    .addComponent(lblPhoneCus)
                                    .addComponent(lblTypeCus))
                                .addGap(32, 32, 32)
                                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTypeCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhoneCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserNameCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNameCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPasswordCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCityCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddressCust, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastNameCust, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        pnlRegistrarCustLayout.setVerticalGroup(
            pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                        .addComponent(btnAtrasCus)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarCustLayout.createSequentialGroup()
                        .addComponent(lblCheckCust, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserNameCus)
                    .addComponent(txtUserNameCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdCus)
                    .addComponent(txtIdCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastNameCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasswordCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCityCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddressCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddressCus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrarCustLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblNameCus)
                        .addGap(32, 32, 32)
                        .addComponent(lblLastnameCus)
                        .addGap(28, 28, 28)
                        .addComponent(lblPasswordCus)
                        .addGap(18, 18, 18)
                        .addComponent(lblCityCus)))
                .addGap(23, 23, 23)
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneCus)
                    .addComponent(txtPhoneCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(pnlRegistrarCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeCus)
                    .addComponent(txtTypeCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCust)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRegistrarCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 450, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCus;
    private javax.swing.JButton btnRegistrarCust;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAddressCus;
    private javax.swing.JLabel lblCheckCust;
    private javax.swing.JLabel lblCityCus;
    private javax.swing.JLabel lblColorCust;
    private javax.swing.JLabel lblIdCus;
    private javax.swing.JLabel lblLastnameCus;
    private javax.swing.JLabel lblNameCus;
    private javax.swing.JLabel lblPasswordCus;
    private javax.swing.JLabel lblPhoneCus;
    private javax.swing.JLabel lblTypeCus;
    private javax.swing.JLabel lblUserNameCus;
    private javax.swing.JPanel pnlColorCustomer;
    private javax.swing.JPanel pnlRegistrarCust;
    private javax.swing.JTextField txtAddressCust;
    private javax.swing.JTextField txtCityCust;
    private javax.swing.JTextField txtIdCust;
    private javax.swing.JTextField txtLastNameCust;
    private javax.swing.JTextField txtNameCust;
    private javax.swing.JTextField txtPasswordCust;
    private javax.swing.JTextField txtPhoneCust;
    private javax.swing.JTextField txtTypeCust;
    private javax.swing.JTextField txtUserNameCust;
    // End of variables declaration//GEN-END:variables
    private void initIcons() {
    
    
        addIcon(lblColorCust, "src/main/java/resource/fondocust.png");
        addIcon(lblCheckCust, "src/main/java/resource/checkcust.png");
        //addIcon(lblLupa, "src/main/java/resource/buscar.png");
       // addIcon(lblMas, "src/main/java/resource/registrar.png");
    }
    private void addIcon(JLabel lb, String pathIcon) 
    {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }
}
