/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurantathand.client.presentation;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Michelle Vallejo
 */
public class GUIRLoginRest extends javax.swing.JFrame 
{

    /**
     * Creates new form GUIRLoginRest
     */
   
    public GUIRLoginRest() 
    {
        
        initComponents();
       setLocationRelativeTo(null);
       
        initIcons();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlColorLogin = new javax.swing.JPanel();
        lblLogoRest = new javax.swing.JLabel();
        pnlLoginRest = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblUserRest = new javax.swing.JLabel();
        lblPassRest = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblSignIn = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblRecoverPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlColorLogin.setBackground(new java.awt.Color(76, 174, 235));

        javax.swing.GroupLayout pnlColorLoginLayout = new javax.swing.GroupLayout(pnlColorLogin);
        pnlColorLogin.setLayout(pnlColorLoginLayout);
        pnlColorLoginLayout.setHorizontalGroup(
            pnlColorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLoginLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblLogoRest, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnlColorLoginLayout.setVerticalGroup(
            pnlColorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLoginLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblLogoRest, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        getContentPane().add(pnlColorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 420));

        pnlLoginRest.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginRest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(null);
        pnlLoginRest.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 200, 20));

        jTextField2.setBorder(null);
        pnlLoginRest.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, 20));

        lblUserRest.setForeground(new java.awt.Color(102, 102, 102));
        pnlLoginRest.add(lblUserRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 50));

        lblPassRest.setForeground(new java.awt.Color(102, 102, 102));
        lblPassRest.setText(" ");
        pnlLoginRest.add(lblPassRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 40));

        btnLogin.setBackground(new java.awt.Color(76, 110, 235));
        btnLogin.setText("Enter");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlLoginRest.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 263, 90, 30));
        pnlLoginRest.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, 10));
        pnlLoginRest.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, -1));

        lblSignIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(102, 102, 102));
        pnlLoginRest.add(lblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 160, 120));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setForeground(new java.awt.Color(51, 0, 204));
        btnRegistrar.setText("Sign Up");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlLoginRest.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, -1));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("If you be new customer");
        pnlLoginRest.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lblRecoverPass.setForeground(new java.awt.Color(51, 0, 204));
        lblRecoverPass.setText("Recover Password");
        pnlLoginRest.add(lblRecoverPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        getContentPane().add(pnlLoginRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 320, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRLoginRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRLoginRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRLoginRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRLoginRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRLoginRest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblLogoRest;
    private javax.swing.JLabel lblPassRest;
    private javax.swing.JLabel lblRecoverPass;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblUserRest;
    private javax.swing.JPanel pnlColorLogin;
    private javax.swing.JPanel pnlLoginRest;
    // End of variables declaration//GEN-END:variables
   
private void initIcons() {
    
    
        addIcon(lblUserRest, "src/main/java/resource/Username.png");
        addIcon(lblPassRest, "src/main/java/resource/Password.png");
        addIcon(lblLogoRest, "src/main/java/resource/logoRest.png");
        addIcon(lblSignIn, "src/main/java/resource/welcome.png");
    }
    private void addIcon(JLabel lb, String pathIcon) {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }
}
