/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurantathand.client.presentation;

import co.unicauca.restaurantathand.client.access.Factory;
import co.unicauca.restaurantathand.client.access.IRestaurantAccess;
import co.unicauca.restaurantathand.client.domain.services.RestaurantService;
import static co.unicauca.restaurantathand.client.infra.Messages.successMessage;
import co.unicauca.restaurantathand.commons.domain.Restaurant;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author MANNUEL
 */
public class GUIRegistrationRest extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistrationRest
     */
    public GUIRegistrationRest() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("src/main/java/resource/bg2.png");
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                jLbLogo.getWidth(),
                jLbLogo.getHeight(),
                Image.SCALE_AREA_AVERAGING));
        jLbLogo.setIcon(icono);
        this.repaint();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroRest = new javax.swing.JPanel();
        lblNitRest = new java.awt.Label();
        lblNameRest = new java.awt.Label();
        lblAddressRest = new java.awt.Label();
        lblMobileRest = new java.awt.Label();
        lblEmailRest = new java.awt.Label();
        lblIdAdminRest = new java.awt.Label();
        txtNitRest = new java.awt.TextField();
        txtNameRest = new java.awt.TextField();
        txtAddressRest = new java.awt.TextField();
        txtMobileRest = new java.awt.TextField();
        txtEmailRest = new java.awt.TextField();
        txtIdAdminRest = new java.awt.TextField();
        btnRegistrarRest = new javax.swing.JButton();
        btnBuscarRest = new javax.swing.JButton();
        jLbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRegistroRest.setBackground(new java.awt.Color(255, 255, 255));

        lblNitRest.setText("Nit:");

        lblNameRest.setText("Nombre:");

        lblAddressRest.setText("Direccion:");

        lblMobileRest.setText("Telefono:");

        lblEmailRest.setText("Correo:");

        lblIdAdminRest.setText("Id Administrador:");

        btnRegistrarRest.setText("REGISTRAR");
        btnRegistrarRest.setName("REGISTRAR"); // NOI18N
        btnRegistrarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRestActionPerformed(evt);
            }
        });

        btnBuscarRest.setText("BUSCAR");
        btnBuscarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroRestLayout = new javax.swing.GroupLayout(pnlRegistroRest);
        pnlRegistroRest.setLayout(pnlRegistroRestLayout);
        pnlRegistroRestLayout.setHorizontalGroup(
            pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroRestLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMobileRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddressRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNitRest, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarRest)
                            .addComponent(lblIdAdminRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdAdminRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobileRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarRest))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNitRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameRest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        pnlRegistroRestLayout.setVerticalGroup(
            pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNitRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNitRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddressRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddressRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                        .addComponent(jLbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroRestLayout.createSequentialGroup()
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMobileRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobileRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblEmailRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistroRestLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(lblIdAdminRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIdAdminRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(pnlRegistroRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarRest)
                    .addComponent(btnBuscarRest))
                .addGap(62, 62, 62))
        );

        lblNitRest.getAccessibleContext().setAccessibleName("lblNitRest");
        lblNameRest.getAccessibleContext().setAccessibleName("lblNameRest");
        lblAddressRest.getAccessibleContext().setAccessibleName("lblAddressRest");
        lblMobileRest.getAccessibleContext().setAccessibleName("lblMobileRest");
        lblEmailRest.getAccessibleContext().setAccessibleName("lblEmailRest");
        lblIdAdminRest.getAccessibleContext().setAccessibleName("lblIdAdmiRest");
        txtNitRest.getAccessibleContext().setAccessibleName("txtNitRest");
        txtNameRest.getAccessibleContext().setAccessibleName("txtNameRest");
        txtAddressRest.getAccessibleContext().setAccessibleName("txtAddressRest");
        txtMobileRest.getAccessibleContext().setAccessibleName("txtMobileRest");
        txtEmailRest.getAccessibleContext().setAccessibleName("txtEmailRest");
        txtIdAdminRest.getAccessibleContext().setAccessibleName("txtIdAdminRest");
        btnRegistrarRest.getAccessibleContext().setAccessibleName("btnRegistrarRest");
        btnRegistrarRest.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlRegistroRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRestActionPerformed
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        // Inyecta la dependencia
        RestaurantService objRestaurantService = new RestaurantService(service);
        // TODO add your handling code here:
        Restaurant objRestaurant = new Restaurant();
        objRestaurant.setAtrNitRest(txtNitRest.getText());
        objRestaurant.setAtrNameRest(txtNameRest.getText());
        objRestaurant.setAtrAddressRest(txtAddressRest.getText());
        objRestaurant.setAtrMobileRest(txtMobileRest.getText());
        objRestaurant.setAtrEmailRest(txtEmailRest.getText());
       // objRestaurant.setAtrAdminRest(txtIdAdminRest.getText());
       
        try {
            String response = objRestaurantService.createRestaurant(objRestaurant);
            successMessage("Cliente "+ response + " agregado con éxito.", "Atención");
            clearControls();
            txtNitRest.setText("");
            btnRegistrarRest.setVisible(false);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btnRegistrarRestActionPerformed

    private void btnBuscarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRestActionPerformed
        String nit = txtNitRest.getText().trim();
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        
        RestaurantService objRestaurantService = new RestaurantService(service);
        Restaurant objRestaurant;
        try
        {
            objRestaurant = objRestaurantService.findRestaurant(nit);
            successMessage("Funciono"+objRestaurant.getAtrNitRest(), "Atencion");
            txtNitRest.setText("");
        }
        catch(Exception ex)
        {
           successMessage(ex.getMessage(), "Atencion"); 
        }
                
    }//GEN-LAST:event_btnBuscarRestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrationRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrationRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrationRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrationRest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrationRest().setVisible(true);
            }
        });
    }
    private void clearControls() 
    {
        txtAddressRest.setText("");
        txtEmailRest.setText("");
        txtIdAdminRest.setText("");
        txtMobileRest.setText("");
        txtNameRest.setText("");
        txtNitRest.setText("");   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRest;
    private javax.swing.JButton btnRegistrarRest;
    private javax.swing.JLabel jLbLogo;
    private java.awt.Label lblAddressRest;
    private java.awt.Label lblEmailRest;
    private java.awt.Label lblIdAdminRest;
    private java.awt.Label lblMobileRest;
    private java.awt.Label lblNameRest;
    private java.awt.Label lblNitRest;
    private javax.swing.JPanel pnlRegistroRest;
    private java.awt.TextField txtAddressRest;
    private java.awt.TextField txtEmailRest;
    private java.awt.TextField txtIdAdminRest;
    private java.awt.TextField txtMobileRest;
    private java.awt.TextField txtNameRest;
    private java.awt.TextField txtNitRest;
    // End of variables declaration//GEN-END:variables

    
}
