/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurantathand.client.presentation;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Michelle Vallejo
 */
public class GUIRegistroMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistroMenu
     */
    public GUIRegistroMenu() {
        initComponents();
        setLocationRelativeTo(null);
        initIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlValidateIdMenu = new javax.swing.JPanel();
        lblIdMenuRest = new javax.swing.JLabel();
        txtIdMenuRest = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pnlRegistrarMenuRest = new javax.swing.JPanel();
        lblNameMenuRest = new javax.swing.JLabel();
        txtNameMenuRest = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblDateMenuRest = new javax.swing.JLabel();
        btnRegistrarRest = new javax.swing.JButton();
        cbxTypeMenuRes = new javax.swing.JComboBox<>();
        lblRegMenu = new javax.swing.JLabel();
        btnSearchIdMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        pnlValidateIdDish = new javax.swing.JPanel();
        lblRegDish = new javax.swing.JLabel();
        lblIdDish = new javax.swing.JLabel();
        txtIdDishRes = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        pnlRegistrarPlatp = new javax.swing.JPanel();
        lblNameDish = new javax.swing.JLabel();
        txtNameDish = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cbxTypeDishRes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnSearchIdPlato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlValidateIdMenu.setBackground(new java.awt.Color(255, 204, 204));

        lblIdMenuRest.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblIdMenuRest.setForeground(new java.awt.Color(102, 102, 102));
        lblIdMenuRest.setText("Identification:");

        txtIdMenuRest.setBackground(new java.awt.Color(255, 204, 204));
        txtIdMenuRest.setBorder(null);

        pnlRegistrarMenuRest.setBackground(new java.awt.Color(255, 204, 204));

        lblNameMenuRest.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNameMenuRest.setForeground(new java.awt.Color(102, 102, 102));
        lblNameMenuRest.setText("Name: ");

        txtNameMenuRest.setBackground(new java.awt.Color(255, 204, 204));
        txtNameMenuRest.setBorder(null);

        lblDateMenuRest.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDateMenuRest.setForeground(new java.awt.Color(102, 102, 102));
        lblDateMenuRest.setText("Type menu:");

        btnRegistrarRest.setText("Register");

        cbxTypeMenuRes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbxTypeMenuRes.setForeground(new java.awt.Color(102, 102, 102));
        cbxTypeMenuRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Executive", "Stream", " ", " " }));

        javax.swing.GroupLayout pnlRegistrarMenuRestLayout = new javax.swing.GroupLayout(pnlRegistrarMenuRest);
        pnlRegistrarMenuRest.setLayout(pnlRegistrarMenuRestLayout);
        pnlRegistrarMenuRestLayout.setHorizontalGroup(
            pnlRegistrarMenuRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrarMenuRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                        .addComponent(lblNameMenuRest)
                        .addGap(10, 10, 10)
                        .addComponent(txtNameMenuRest, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                        .addComponent(lblDateMenuRest)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTypeMenuRes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnRegistrarRest)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlRegistrarMenuRestLayout.setVerticalGroup(
            pnlRegistrarMenuRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrarMenuRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameMenuRest)
                    .addGroup(pnlRegistrarMenuRestLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNameMenuRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pnlRegistrarMenuRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateMenuRest)
                    .addComponent(cbxTypeMenuRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnRegistrarRest)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnSearchIdMenu.setText("Search");

        javax.swing.GroupLayout pnlValidateIdMenuLayout = new javax.swing.GroupLayout(pnlValidateIdMenu);
        pnlValidateIdMenu.setLayout(pnlValidateIdMenuLayout);
        pnlValidateIdMenuLayout.setHorizontalGroup(
            pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidateIdMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidateIdMenuLayout.createSequentialGroup()
                        .addComponent(lblRegMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValidateIdMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValidateIdMenuLayout.createSequentialGroup()
                                .addComponent(lblIdMenuRest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(txtIdMenuRest, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchIdMenu)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValidateIdMenuLayout.createSequentialGroup()
                                .addComponent(pnlRegistrarMenuRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
        );
        pnlValidateIdMenuLayout.setVerticalGroup(
            pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValidateIdMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdMenuRest)
                    .addGroup(pnlValidateIdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdMenuRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchIdMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegistrarMenuRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        getContentPane().add(pnlValidateIdMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 360));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 60));

        pnlValidateIdDish.setBackground(new java.awt.Color(204, 255, 204));

        lblIdDish.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblIdDish.setForeground(new java.awt.Color(102, 102, 102));
        lblIdDish.setText("Identification:");

        txtIdDishRes.setBackground(new java.awt.Color(204, 255, 204));
        txtIdDishRes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtIdDishRes.setBorder(null);

        pnlRegistrarPlatp.setBackground(new java.awt.Color(204, 255, 204));

        lblNameDish.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNameDish.setForeground(new java.awt.Color(102, 102, 102));
        lblNameDish.setText("Name:");

        txtNameDish.setBackground(new java.awt.Color(204, 255, 204));
        txtNameDish.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Type dish:");

        cbxTypeDishRes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbxTypeDishRes.setForeground(new java.awt.Color(102, 102, 102));
        cbxTypeDishRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Special dish", "Dish of the day" }));

        jButton1.setText("Register");

        javax.swing.GroupLayout pnlRegistrarPlatpLayout = new javax.swing.GroupLayout(pnlRegistrarPlatp);
        pnlRegistrarPlatp.setLayout(pnlRegistrarPlatpLayout);
        pnlRegistrarPlatpLayout.setHorizontalGroup(
            pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarPlatpLayout.createSequentialGroup()
                .addGroup(pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlRegistrarPlatpLayout.createSequentialGroup()
                            .addComponent(lblNameDish)
                            .addGap(28, 28, 28)
                            .addGroup(pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5)
                                .addComponent(txtNameDish, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                        .addGroup(pnlRegistrarPlatpLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxTypeDishRes, 0, 1, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlRegistrarPlatpLayout.setVerticalGroup(
            pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarPlatpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameDish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarPlatpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxTypeDishRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnSearchIdPlato.setText("Search");

        javax.swing.GroupLayout pnlValidateIdDishLayout = new javax.swing.GroupLayout(pnlValidateIdDish);
        pnlValidateIdDish.setLayout(pnlValidateIdDishLayout);
        pnlValidateIdDishLayout.setHorizontalGroup(
            pnlValidateIdDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidateIdDishLayout.createSequentialGroup()
                .addGroup(pnlValidateIdDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlValidateIdDishLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblIdDish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlValidateIdDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(txtIdDishRes, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchIdPlato))
                    .addGroup(pnlValidateIdDishLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblRegDish, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlValidateIdDishLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRegistrarPlatp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlValidateIdDishLayout.setVerticalGroup(
            pnlValidateIdDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValidateIdDishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegDish, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlValidateIdDishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdDish)
                    .addComponent(txtIdDishRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchIdPlato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegistrarPlatp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(pnlValidateIdDish, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 290, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /**
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistroMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRest;
    private javax.swing.JButton btnSearchIdMenu;
    private javax.swing.JButton btnSearchIdPlato;
    private javax.swing.JComboBox<String> cbxTypeDishRes;
    private javax.swing.JComboBox<String> cbxTypeMenuRes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDateMenuRest;
    private javax.swing.JLabel lblIdDish;
    private javax.swing.JLabel lblIdMenuRest;
    private javax.swing.JLabel lblNameDish;
    private javax.swing.JLabel lblNameMenuRest;
    private javax.swing.JLabel lblRegDish;
    private javax.swing.JLabel lblRegMenu;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPanel pnlRegistrarMenuRest;
    private javax.swing.JPanel pnlRegistrarPlatp;
    private javax.swing.JPanel pnlValidateIdDish;
    private javax.swing.JPanel pnlValidateIdMenu;
    private javax.swing.JTextField txtIdDishRes;
    private javax.swing.JTextField txtIdMenuRest;
    private javax.swing.JTextField txtNameDish;
    private javax.swing.JTextField txtNameMenuRest;
    // End of variables declaration//GEN-END:variables
private void initIcons() {
    
    
        addIcon(lblRegistrar, "src/main/java/resource/registrarmenu.png");
        addIcon(lblRegMenu, "src/main/java/resource/menu.png");
        addIcon(lblRegDish, "src/main/java/resource/logoDish.png");
       
    }
    private void addIcon(JLabel lb, String pathIcon) {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }
}
