/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.restaurantathand.client.presentation;

import co.unicauca.restaurantathand.client.access.Factory;
import co.unicauca.restaurantathand.client.access.IRestaurantAccess;
import co.unicauca.restaurantathand.client.domain.services.RestaurantService;
import static co.unicauca.restaurantathand.client.infra.Messages.successMessage;
import co.unicauca.restaurantathand.commons.domain.Restaurant;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author MANNUEL
 */
public class GUIRegistrationRest extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistrationRest
     */
    public GUIRegistrationRest() {
        initComponents();
        setLocationRelativeTo(null);
        initIcons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroRest = new javax.swing.JPanel();
        lblNitRest = new java.awt.Label();
        lblNameRest = new java.awt.Label();
        lblAddressRest = new java.awt.Label();
        lblMobileRest = new java.awt.Label();
        lblEmailRest = new java.awt.Label();
        btnRegistrarRest = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNitRest = new javax.swing.JTextField();
        txtNameRest = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtAddressRest = new javax.swing.JTextField();
        txtMobileRest = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtEmailRest = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCheckIn = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblCiudadRest = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtCiudad = new javax.swing.JTextField();
        pnlColorRegistrar = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistroRest.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistroRest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNitRest.setForeground(new java.awt.Color(102, 102, 102));
        lblNitRest.setText("Nit:");
        pnlRegistroRest.add(lblNitRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 41, 20));
        lblNitRest.getAccessibleContext().setAccessibleName("lblNitRest");

        lblNameRest.setForeground(new java.awt.Color(102, 102, 102));
        lblNameRest.setText("Name:");
        pnlRegistroRest.add(lblNameRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));
        lblNameRest.getAccessibleContext().setAccessibleName("lblNameRest");

        lblAddressRest.setForeground(new java.awt.Color(102, 102, 102));
        lblAddressRest.setText("Address:");
        pnlRegistroRest.add(lblAddressRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));
        lblAddressRest.getAccessibleContext().setAccessibleName("lblAddressRest");

        lblMobileRest.setForeground(new java.awt.Color(102, 102, 102));
        lblMobileRest.setText("Phone:");
        pnlRegistroRest.add(lblMobileRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 20));
        lblMobileRest.getAccessibleContext().setAccessibleName("lblMobileRest");

        lblEmailRest.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailRest.setText("Email:");
        pnlRegistroRest.add(lblEmailRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));
        lblEmailRest.getAccessibleContext().setAccessibleName("lblEmailRest");

        btnRegistrarRest.setText("Check In");
        btnRegistrarRest.setName("REGISTRAR"); // NOI18N
        btnRegistrarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRestActionPerformed(evt);
            }
        });
        pnlRegistroRest.add(btnRegistrarRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));
        btnRegistrarRest.getAccessibleContext().setAccessibleName("btnRegistrarRest");
        btnRegistrarRest.getAccessibleContext().setAccessibleDescription("");

        pnlRegistroRest.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 10));

        txtNitRest.setBorder(null);
        pnlRegistroRest.add(txtNitRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 20));

        txtNameRest.setBorder(null);
        pnlRegistroRest.add(txtNameRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, 20));
        pnlRegistroRest.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, 10));
        pnlRegistroRest.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 10));

        txtAddressRest.setBorder(null);
        pnlRegistroRest.add(txtAddressRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 20));

        txtMobileRest.setBorder(null);
        pnlRegistroRest.add(txtMobileRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, 20));
        pnlRegistroRest.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 200, 10));

        txtEmailRest.setBorder(null);
        pnlRegistroRest.add(txtEmailRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, 20));
        pnlRegistroRest.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 200, 10));
        pnlRegistroRest.add(lblCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, 110));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setForeground(new java.awt.Color(102, 102, 102));
        btnAtras.setText("Back");
        btnAtras.setBorder(null);
        pnlRegistroRest.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        lblCiudadRest.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCiudadRest.setForeground(new java.awt.Color(102, 102, 102));
        lblCiudadRest.setText("City:");
        pnlRegistroRest.add(lblCiudadRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 250, 50, 20));
        pnlRegistroRest.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 10));

        txtCiudad.setBorder(null);
        pnlRegistroRest.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 200, -1));

        getContentPane().add(pnlRegistroRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 440, 440));

        pnlColorRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        pnlColorRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlColorRegistrar.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 440));

        getContentPane().add(pnlColorRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRestActionPerformed
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        // Inyecta la dependencia
        RestaurantService objRestaurantService = new RestaurantService(service);
        // TODO add your handling code here:
        Restaurant objRestaurant = new Restaurant();
        objRestaurant.setAtrNitRest(txtNitRest.getText());
        objRestaurant.setAtrNameRest(txtNameRest.getText());
        objRestaurant.setAtrAddressRest(txtAddressRest.getText());
        objRestaurant.setAtrMobileRest(txtMobileRest.getText());
        objRestaurant.setAtrEmailRest(txtEmailRest.getText());
       // objRestaurant.setAtrAdminRest(txtIdAdminRest.getText());
       
        try {
            String response = objRestaurantService.createRestaurant(objRestaurant);
            successMessage("Cliente "+ response + " agregado con éxito.", "Atención");
            clearControls();
            txtNitRest.setText("");
            btnRegistrarRest.setVisible(false);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btnRegistrarRestActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
   
    private void clearControls() 
    {
        txtAddressRest.setText("");
        txtEmailRest.setText("");
        //txtIdAdminRest.setText("");
        txtMobileRest.setText("");
        txtNameRest.setText("");
        txtNitRest.setText("");   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarRest;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private java.awt.Label lblAddressRest;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCiudadRest;
    private java.awt.Label lblEmailRest;
    private javax.swing.JLabel lblFondo;
    private java.awt.Label lblMobileRest;
    private java.awt.Label lblNameRest;
    private java.awt.Label lblNitRest;
    private javax.swing.JPanel pnlColorRegistrar;
    private javax.swing.JPanel pnlRegistroRest;
    private javax.swing.JTextField txtAddressRest;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEmailRest;
    private javax.swing.JTextField txtMobileRest;
    private javax.swing.JTextField txtNameRest;
    private javax.swing.JTextField txtNitRest;
    // End of variables declaration//GEN-END:variables

 private void initIcons() {
    
    
        addIcon(lblFondo, "src/main/java/resource/fondo.png");
        addIcon(lblCheckIn, "src/main/java/resource/check.png");
        //addIcon(lblLupa, "src/main/java/resource/buscar.png");
       // addIcon(lblMas, "src/main/java/resource/registrar.png");
    }
    private void addIcon(JLabel lb, String pathIcon) 
    {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }   
}
